controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_joint
      - forearm_joint
      - upper_arm_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - gripper_l_finger_joint